name: "metal-capitol"

services:
  http-server:
    image: nginx
    volumes:
      - type: bind
        source: /home/hugo/dev/metalcapitol/out/web
        target: /var/web
    configs:
        - source: nginx-conf
          target: /etc/nginx/nginx.conf
    ports:
      - "8080:80"
configs:
  nginx-conf:
    file: ./nginx.conf

